### ISSUE TITLE
There is an issue when user create a trading account(extension), once after delete the trading account(extension)

### ISSUE THREAD

**Issue by Hildajose** [Polkadex-Substrate/Polkadex-Orderbook-Frontend#1264]
# 📝 Bug Description
The "confirm transaction" pop-up displayed "your balance is not enough to pay the fee"for creating the trading account(extension) even after that, the user can view  the trading account was created in the "Registered trading accounts" button. And there is a enough balance is there

## 🤔 Expected Behavior
If that Alert is displayed in the "confirm pop-up" the user should not be able to view the trading account in the "Registered trading 
accounts" button **(But there is enough balance to create the trading account)**

## 😯 Current Behavior
There is enough balance in PDEX, but in the "confirm transaction displayed "your balance is not enough to pay the fee" while creating a trading account(extension)
message and stack trace, video link or screenshot -->

## 🔎 Steps to Reproduce

1. Delete the trading account(extension)
2. displayed "Register funding account" button
3. Click "Register funding account" button 
4. automatically log out from the account
5. login with funding account
6.  Click "Register funding account" button 
7. "sign and submit" button
8. In "confirm transaction" pop-up displayed "your  balance is not enough to pay the fee"
9. click cancel button
10. verify the user able to view the trading account(extension) in "Registered trading accounts" button 

## 🌍 Your Environment

| Software         | Version(s)                  |
| ---------------- | --------------------------- |
| Project/Package  |                             |
| Browser          | []Chrome []Firefox []Safari |
| Operating System | []Windows []MacOS []Linux   |

**Comment by ap211unitech** [comment]
Your funding account balance is 1.01060582 PDEX. 
and Estimated fee = 0.0141 PDEX

Remaining balance (if transaction gets successful) = 1.01060582 - 0.0141 = 0.99650582 PDEX 
which can't be possible as it goes below 1 PDEX which is existential deposit, that's why it's saying `not enough balance to pay fee` which is correct behavior.

**Comment by Hildajose** [comment]
so that information must be convey to the user right?

**Comment by ap211unitech** [comment]
Added Existential Value in PopUp which will make user know that there is a minimum balance required in account that's why they can't sign the transaction.

<img width="388" alt="image" src="https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/65214523/fbebaccc-9a14-404a-a740-d6504761d05a">

**Comment by ap211unitech** [comment]
[PR](https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/pull/1266) is up for fixing it.

**Comment by Hildajose** [comment]
Ok got it
